name: concurrency workflow
on:
  push:
  workflow_dispatch: 

jobs:
  job-1:
    runs-on: ubuntu-latest
    concurrency:
      group: staging_environment
      cancel-in-progress: true
    steps:
      - name: print hello from job1
        run: |
          echo "Hellow from job1"
          sleep 360
  job-2:
    runs-on: ubuntu-latest
    concurrency:
      group: staging_environment
      cancel-in-progress: true
    steps:
      - name: Hello from job2
        run: |
          echo "Welcome from job2"
  job-3:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [job-1, job-2]
    steps:
      - name:  hello from job-3
        run: |
          echo "Hello from job-3"