name: First workflow
on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome to demo job
              run: echo "Welcome to github action certification"
            - name: Checkout the code repo
              uses: actions/checkout@v5
            - name: Read and list the file from repo
              run:  | 
                ls -lrta
                cat README.md
            - name: Generate ASCII Art work
              run: cowsay -f dragon "Welcome to the dragon" >> dragon.txt
            

