name: Generate Ascii art work
on:
  push
jobs:
    build_job_1:
        runs-on: [ linux-ubuntu,self-hosted]
        steps:
        - name: Install cowsay program
          run: sudo apt install cowsay -y
        - name: Execute cowsay cmd
          run: cowsay -f dragon "Welcome to the dragon" >> dragon.txt
        - name: Upload the dragon txt file
          uses: actions/upload-artifact@v4
          with:
            name: dragonfile
            path: dragon.txt
    test_job_1:
        runs-on: ubuntu-latest
        needs: build_job_1
        steps:
        - name: Download dragon txt file
          uses: actions/download-artifact@v5
          with:
            name: dragonfile
        - name: list the file
          run: ls -lrth
        - name: Test the file exists
          run: grep -i "dragon" dragon.txt
    deploy_job_1:
        runs-on: ubuntu-latest
        needs: test_job_1
        steps:
        - name: Download dragon txt file
          uses: actions/download-artifact@v5
          with:
            name: dragonfile        
        - name: View the dragon.txt file
          run: cat dragon.txt
        - name: List file in the repo
          run: ls -lrth

