name: Generate Ascii art work
on:
  push
jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Install cowsay program
          run: sudo apt install cowsay -y
        - name: Execute cowsay cmd
          run: cowsay -f dragon "Welcome to the dragon" >> dragon.txt
        - name: Sleep for 30s
          run: sleep 30
    test_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Test the file exists
          run: grep -i "dragon" dragon.txt
        - name: sleep for 30s
          run: sleep 30
    deploy_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: View the dragon.txt file
          run: cat dragon.txt
        - name: List file in the repo
          run: ls -lrth
