name: Github env workflow
on: 
  workflow_dispatch:
  push:
jobs:
  demo_env:
    runs-on: ubuntu-latest
    steps:
      - name: Store the variable as GITHUB_ENV
        run: |
          echo "DOCKER_USERNMAE=iamdevops993" >> $GITHUB_ENV
          echo "PROD_DEPLOY=true" >> $GITHUB_ENV
      - name: Group the message
        run:  |
          echo "::group::My group messages"
          echo "Welcome to iamdevops repository"
          echo "Find the new codes and scripts"
          echo "::endgroup"

      - name: Retrive the env
        run: |
          echo $DOCKER_USERNMAE
          echo $PROD_DEPLOY