name: Vault Integration

on:
  workflow_dispatch: 
  push:
    branches: [ main ]

permissions:
  id-token: write   # REQUIRED for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Vault
        uses: hashicorp/vault-action@v3
        with:
          url: https://8200-port-acq663rglmdniflx.labs.kodekloud.com
          method: jwt
          jwtGithubAudience: sts.amazonaws.com
          role: github-actions
          secrets: |
            kv/data/db username | DB_USER ;
            kv/data/db password | DB_PASS

      - name: Use secrets
        run: |
          echo "DB_USER=$DB_USER"
