name: Matrix configuration

on: [push,workflow_dispatch]
jobs:
    docker_build_linux:
        runs-on: ubuntu-latest
        steps:
            - name: Docker info
              run: docker info
            - name: Run docker helloworld container
              run: docker run hello-world
    docker_build_windows:
        runs-on: windows-latest
        steps:
            - name: Docker info
              run: docker info
            - name: Run docker helloworld container
              run: docker run hello-world