name: OpenID connect workflow
permissions: 
  id-token: write
  contents: read
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: configure aws OIDC
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: arn:aws:iam::012584563464:role/openIDRole
          aws-region: us-east-1
      - name: List the bucket in AWS
        run: |
          echo "Welcome to OIDC connect to aws"
          echo "listing the s3 bucket"
          aws s3 ls
      - name: list the file in the s3 bucket
        run: | 
          echo "List the file in the specific bucket"
          aws s3 ls s3://mybucket-open-id
