name: "Webhook event trigger"
on:
    repository_dispatch: 
        types:
            - Webhook
jobs:
    webhook-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v6
            - name: Run the script
              run: echo "Welcome to the github action $GITHUB_EVENT_TYPE"